name: ci

on:
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:latest
      - name: Delete old images
        uses: snok/container-retention-policy@v1
        with:
          image-names: 'are-you-ok-bot'
          keep-at-least: 3
          account-type: personal
          token: ${{ secrets.PAT }}
#      - name: Docker repo cleanup
#        uses: actions/delete-package-versions@v3
#        with:
#          owner: 'github'
#          repo: 'packages'
#          package-name: 'test-package'
#          token: ${{ secrets.PAT }}
#          min-versions-to-keep: 2
#          package-name: 'are-you-ok-bot'
#          min-versions-to-keep: 3
##          token: ${{ secrets.PAT }}
      - name: GitHub tags cleanup #https://github.com/dev-drprasad/delete-older-releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
#          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ github.token }}
