name: ci

on:
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/prod/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}:latest
      - name: Delete old images
        uses: snok/container-retention-policy@v1
        with:
          image-names: are-you-ok-bot
          cut-off: 1 minute ago UTC
          skip-tags: latest
          keep-at-least: 3
          account-type: personal
          token: ${{ secrets.PAT }} # token with delete:packages and read:packages enabled permissions
      - name: GitHub tags cleanup #https://github.com/dev-drprasad/delete-older-releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
